export const showTranslationBtn = 'Показать перевод'
export const showPronouncingBtn = 'Показать произношение'
export const firstListItemClassName = 'word-item'
export const nextBtnClassName = 'btn btn-primary'
export const nextBtnCaption = 'Дальше'
export const wordCardBtnClassName = 'btn btn-outline-secondary'
