export const showTranslationBtn = 'Показать перевод'
export const showPronouncingBtn = 'Показать произношение'
export const firstListItemClassName = 'word-item'
export const nextBtnClassName = 'btn btn-success'
export const nextBtnCaption = 'Далее'
export const wordCardBtnClassName = 'btn btn-outline-secondary'
